server.port=8082
spring.jackson.date-format=com.dealerengine.www.RFC3339DateFormat
spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS=false
spring.data.mongo.host=localhost
spring.data.mongo.port=27017
spring.data.mongo.database=mazda